/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/twoone.ts" />
/// <reference path="../scenes/twotwo.ts" />
/// <reference path="../scenes/threeone.ts" />
/// <reference path="../scenes/threetwo.ts" />
/// <reference path="../scenes/threethree.ts" />
/// <reference path="../scenes/threefour.ts" />
/// <reference path="../scenes/fourone.ts" />
/// <reference path="../scenes/fourtwo.ts" />
/// <reference path="../scenes/fourthree.ts" />
/// <reference path="../scenes/fourfour.ts" />
/// <reference path="../scenes/fourfive.ts" />
/// <reference path="../scenes/foursix.ts" />
/// <reference path="../scenes/fourseven.ts" />
/// <reference path="../scenes/foureight.ts" />
/// <reference path="../scenes/intro.ts" /> 
//# sourceMappingURL=_reference.js.map